// BudgetingAPI.Angular/src/app/nav/nav.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-nav',
	templateUrl: './nav.component.html',
	styleUrls: ['./nav.component.css']
})
export class NavComponent { }

<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Day2Day</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">rosalind.m.wills@gmail.com <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>

// BudgetingAPI.FrontEnd/src/components/shared/nav.jsx
import React, { Component } from 'react';
import { render } from 'react-dom';
import styled from 'styled-components';
import NumberFormat from 'react-number-format';
import { Link } from 'react-router-dom';

const NavRow = styled.nav`
	margin: 0;
	padding: 0;
`;

class Nav extends Component {
	render() {
		return (
			<NavRow className="navbar navbar-inverse navbar-static-top">
				<div className="container-fluid">
					<div className="navbar-header">
						<a className="navbar-brand" href="#">Day2Day</a>
					</div>
					<div id="navbar" className="navbar-collapse collapse">
						<ul className="nav navbar-nav navbar-right">
							<li className="dropdown">
								<a href="#" className="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">rosalind.m.wills@gmail.com <span className="fa fa-caret-down"></span></a>
								<ul className="dropdown-menu">
									<li><Link to="/logout">Logout</Link></li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</NavRow>
		);
	}
}

export default Nav;
